project:
  type: website
  resources:
    - "../data/*.csv"

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

# listing:
#   contents: "*.ipynb"
#   sort: "date desc"
#   type: default
#   categories: true
#   sort-ui: false
#   filter-ui: false