project:
  type: website

output-dir: _site

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: example.ipynb
        text: Example Notebook

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



